Format code

diff --git a/bash-template b/bash-template
--- a/bash-template
+++ b/bash-template
@@ -5,7 +5,7 @@ set -Eeuo pipefail
 trap cleanup SIGINT SIGTERM ERR EXIT
 
 usage() {
-  cat <<EOF
+    cat << EOF
 Usage: $(basename "$0") [-h] [-v] [-f] -p param_value arg1 [arg2...]
 
 Script description here.
@@ -17,87 +17,87 @@ Available options:
 -f, --flag      Some flag description
 -p, --param     Some param description
 EOF
-  exit
+    exit
 }
 
 cleanup() {
-  trap - SIGINT SIGTERM ERR EXIT
-  # script cleanup here
+    trap - SIGINT SIGTERM ERR EXIT
+    # script cleanup here
 }
 
 setup_colors() {
-  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    BLUE='\033[0;34m'
-    CYAN='\033[0;36m'
-    GREEN='\033[0;32m'
-    NOCOLOR='\033[0m'
-    ORANGE='\033[0;33m'
-    PURPLE='\033[0;35m'
-    RED='\033[0;31m'
-    YELLOW='\033[1;33m'
-  else
-    BLUE=''
-    CYAN=''
-    GREEN=''
-    NOCOLOR=''
-    ORANGE=''
-    PURPLE=''
-    RED=''
-    YELLOW=''
-  fi
+    if [[ -t 2 ]] && [[ -z ${NO_COLOR-} ]] && [[ ${TERM-} != "dumb" ]]; then
+        BLUE='\033[0;34m'
+        CYAN='\033[0;36m'
+        GREEN='\033[0;32m'
+        NOCOLOR='\033[0m'
+        ORANGE='\033[0;33m'
+        PURPLE='\033[0;35m'
+        RED='\033[0;31m'
+        YELLOW='\033[1;33m'
+    else
+        BLUE=''
+        CYAN=''
+        GREEN=''
+        NOCOLOR=''
+        ORANGE=''
+        PURPLE=''
+        RED=''
+        YELLOW=''
+    fi
 }
 
 say() {
-  echo >&2 -e "${1-}"
+    echo >&2 -e "${1-}"
 }
 
 die() {
-  local msg=$1
-  local code=${2-1} # default exit status 1
-  msg "$msg"
-  exit "$code"
+    local msg=$1
+    local code=${2-1} # default exit status 1
+    msg "$msg"
+    exit "$code"
 }
 
 parse_params() {
-  # default values of variables set from params
-  flag=0
-  param=''
+    # default values of variables set from params
+    flag=0
+    param=''
 
-  while :; do
-    case "${1-}" in
-    -h | --help)
-      usage
-      ;;
-    -v | --verbose)
-      set -x
-      ;;
-    --no-color)
-      NO_COLOR=1
-      ;;
-    -f | --flag) # example flag
-      flag=1
-      ;;
-    -p | --param) # example named parameter
-      param="${2-}"
-      shift
-      ;;
-    -?*)
-      die "Unknown option: $1"
-      ;;
-    *)
-      break
-      ;;
-    esac
-    shift
-  done
+    while :; do
+        case "${1-}" in
+        -h | --help)
+            usage
+            ;;
+        -v | --verbose)
+            set -x
+            ;;
+        --no-color)
+            NO_COLOR=1
+            ;;
+        -f | --flag) # example flag
+            flag=1
+            ;;
+        -p | --param) # example named parameter
+            param="${2-}"
+            shift
+            ;;
+        -?*)
+            die "Unknown option: $1"
+            ;;
+        *)
+            break
+            ;;
+        esac
+        shift
+    done
 
-  args=("$@")
+    args=("$@")
 
-  # check required params and arguments
-  [[ -z "${param-}" ]] && die "Missing required parameter: param"
-  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+    # check required params and arguments
+    [[ -z ${param-} ]] && die "Missing required parameter: param"
+    [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
 
-  return 0
+    return 0
 }
 
 parse_params "$@"
diff --git a/git-lines b/git-lines
--- a/git-lines
+++ b/git-lines
@@ -5,7 +5,7 @@ set -Eeuo pipefail
 days=${1:-7}
 
 usage() {
-  cat <<EOF
+    cat << EOF
 Usage: $(basename "$0") [-h] [num_days]
 
 Get number of lines committed and deleted.
@@ -15,18 +15,18 @@ Available options:
 -h, --help      Print this help and exit
 num_days        Number of days ago to start from (default 7)
 EOF
-  exit
+    exit
 }
 
 while getopts h opt; do
     case $opt in
-        h)
-            usage
-            ;;
-        *)
-            echo "Invalid flag"
-            exit 1
-            ;;
+    h)
+        usage
+        ;;
+    *)
+        echo "Invalid flag"
+        exit 1
+        ;;
     esac
 done
 
@@ -35,7 +35,7 @@ since_days_ago=$(date --date="${days} days ago" "+%Y-%m-%d")
 since_yesterday=$(date --date="yesterday" "+%Y-%m-%d")
 
 git log --author="${author}" --numstat --pretty="%H" --since "${since_yesterday}" |
-  awk "
+    awk "
     NF==3 {
       plus += \$1;
       minus += \$2;
@@ -46,7 +46,7 @@ git log --author="${author}" --numstat --pretty="%H" --since "${since_yesterday}
   "
 
 git log --author="${author}" --numstat --pretty="%H" --since "${since_days_ago}" |
-  awk "
+    awk "
     NF==3 {
       plus += \$1;
       minus += \$2;
diff --git a/git-unwip b/git-unwip
--- a/git-unwip
+++ b/git-unwip
@@ -6,13 +6,13 @@ username=$(whoami)
 
 while getopts u: opt; do
     case $opt in
-        u)
-            username=$OPTARG
-            ;;
-        *)
-            echo "Invalid flag used"
-            exit 1
-            ;;
+    u)
+        username=$OPTARG
+        ;;
+    *)
+        echo "Invalid flag used"
+        exit 1
+        ;;
     esac
 done
 
diff --git a/setup-remote-shell b/setup-remote-shell
--- a/setup-remote-shell
+++ b/setup-remote-shell
@@ -3,8 +3,8 @@
 set -euo pipefail
 
 if [[ $# -lt 1 ]]; then
-        echo "*** ERROR: no remote SSH target provided (user@host)" >&2
-        exit 1
+    echo "*** ERROR: no remote SSH target provided (user@host)" >&2
+    exit 1
 else
     HOST=$1
 fi
diff --git a/tmux-new-project b/tmux-new-project
--- a/tmux-new-project
+++ b/tmux-new-project
@@ -12,7 +12,10 @@ if [ $# -lt 1 ]; then
 fi
 
 directory=$1
-test -d "$directory" || { echo "ERROR: no directory: $directory" 1>&2; exit 1; }
+test -d "$directory" || {
+    echo "ERROR: no directory: $directory" 1>&2
+    exit 1
+}
 
 (
     cd "$directory"
