Check if fzf command is found

diff --git a/cheatsheet b/cheatsheet
--- a/cheatsheet
+++ b/cheatsheet
@@ -52,6 +52,10 @@ parse_opts() {
 parse_opts "$@"
 shift $((OPTIND - 1))
 
+if ! command -v fzf &> /dev/null; then
+    die "command not found: fzf"
+fi
+
 SELECTED=$(curl -s cht.sh/:list | fzf)
 
 if [[ -z "${SELECTED}" ]]; then
