Fix issues raise with shellcheck

diff --git a/git-unwip b/git-unwip
--- a/git-unwip
+++ b/git-unwip
@@ -8,6 +8,11 @@ while getopts u: opt; do
     case $opt in
         u)
             username=$OPTARG
+            ;;
+        *)
+            echo "Invalid flag used"
+            exit 1
+            ;;
     esac
 done
 
