Add template content to all scripts

diff --git a/pretty-path b/pretty-path
--- a/pretty-path
+++ b/pretty-path
@@ -1,11 +1,60 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
 
-pathtype=${1:-}
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]
 
-if [[ "-m" == "$pathtype" ]]; then
-    printenv MANPATH | tr ":" "\n"
-else
+Pretty print path (PATH or MANPATH) environment variable.
+
+Options:
+    -h      Print this help message and exit
+    -m      Print MANPATH (otherwise PATH)
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts "hm" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            m)
+                PATH_TYPE=true
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
+
+if test -z "${PATH_TYPE}"; then
     printenv PATH | tr ":" "\n"
+else
+    printenv MANPATH | tr ":" "\n"
 fi
diff --git a/pull-all-remote-git b/pull-all-remote-git
--- a/pull-all-remote-git
+++ b/pull-all-remote-git
@@ -1,11 +1,73 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
+
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]
+
+Do "git pull origin " for primary branch in all remote Git repositories.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts ":Cf:hv" optname; do
+        case "${optname}" in
+            f)
+                FOO=${OPTARG}
+                ;;
+            h)
+                usage
+                ;;
+            v)
+                set -x
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 for dir in ~/depot/remote/*/; do
     (
         cd "$dir"
-        echo "### pulling $(pwd)"
-        git pull origin master:master
+        primary_branch=$(git branch --format '%(refname:short)' --list master main | paste -s | awk '{print $1}')
+
+        if test -z "${primary_branch}"; then
+            die "Failed to identify primary Git branch in ${dir}"
+        fi
+
+        echo
+        say "Pull $(pwd) ..."
+        echo
+
+        git pull origin "${primary_branch}:${primary_branch}"
     )
 done
diff --git a/reduce-count b/reduce-count
--- a/reduce-count
+++ b/reduce-count
@@ -1,12 +1,56 @@
 #!/usr/bin/env bash
 
-# Overwrite file, but muiltiply number in first column by 0.75.
+set -Eeuo pipefail
 
-set -euo pipefail
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]
+
+Muiltiply number in first column of a file, in place, by 0.75.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts "h" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 if [[ $# -lt 1 ]]; then
-    echo "### ERROR: no file name provided" >&2
-    exit 1
+    die "No file name provided"
 fi
 
 awk -i inplace 'NF { $1 = sprintf("%d", $1 * 0.75) } 1' "$1"
diff --git a/setup-remote-shell b/setup-remote-shell
--- a/setup-remote-shell
+++ b/setup-remote-shell
@@ -1,14 +1,59 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
+
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] <HOST>
+
+Setup a remote shell environment.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts "h" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 if [[ $# -lt 1 ]]; then
-    echo "*** ERROR: no remote SSH target provided (user@host)" >&2
-    exit 1
-else
-    HOST=$1
+    die "No remote SSH target provided (user@host)"
 fi
 
+HOST=${1}
 SOURCE_DIR=${HOME}/depot/remote/dotfiles
 
 ssh "${HOST}" "rm -f ~/.bash_profile"
diff --git a/tmux-new-project b/tmux-new-project
--- a/tmux-new-project
+++ b/tmux-new-project
@@ -1,23 +1,61 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
 
-# Create a new tmux session in a provided directory.
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] <DIRECTORY>
 
-if [ $# -lt 1 ]; then
-    echo "ERROR: not enough arguments" 1>&2
-    bname=$(basename "$0")
-    echo "usage: $bname <directory>" 1>&2
-    exit 1
-fi
+Create a new tmux session in a provided directory.
 
-directory=$1
-test -d "$directory" || {
-    echo "ERROR: no directory: $directory" 1>&2
-    exit 1
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
 }
 
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts ":Cf:hv" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
+
+directory=${1:-}
+
+if ! test -d "$directory"; then
+    die "Invalid directory: $directory"
+fi
+
 (
-    cd "$directory"
+    cd "${directory}"
     tmux_new_session_pwd
 )
diff --git a/tmux-new-session b/tmux-new-session
--- a/tmux-new-session
+++ b/tmux-new-session
@@ -1,15 +1,58 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
+
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS] <SESSION_NAME>
+
+Create a new tmux session.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts "h" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 if [ $# -lt 1 ]; then
-    echo "ERROR: not enough arguments" 1>&2
-    bname=$(basename "$0")
-    echo "usage: $bname <session_name>" 1>&2
-    exit 1
+    die "Session name not provided"
 fi
 
-# session_name=$(echo "$1" | sed -e 's/[^a-zA-Z0-9]/_/g')
 session_name=${1//[^a-zA-Z0-9]/_/g}
 
 if [ -z "${TMUX:-}" ]; then
diff --git a/update-languages b/update-languages
--- a/update-languages
+++ b/update-languages
@@ -1,6 +1,53 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
+
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]
+
+Update programming languages.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts ":Cf:hv" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 if command -v pyenv 1>/dev/null 2>&1; then
     # Requires pyenv-update plugin.
diff --git a/update-packages b/update-packages
--- a/update-packages
+++ b/update-packages
@@ -1,6 +1,53 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -Eeuo pipefail
+
+usage() {
+    cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [OPTIONS]
+
+Update OS packages.
+
+Options:
+    -h      Print this help message and exit
+EOF
+    exit
+}
+
+say() {
+    echo -e "### ${1-}" >&2
+}
+
+error() {
+    say "ERROR: ${1-}"
+}
+
+die() {
+    error "${1-}"
+    exit "${2-1}"
+}
+
+parse_opts() {
+    while getopts "h" optname; do
+        case "${optname}" in
+            h)
+                usage
+                ;;
+            \?)
+                die "Invalid option: ${OPTARG}"
+                ;;
+            :)
+                die "Invalid option: ${OPTARG} requires an argument"
+                ;;
+            *)
+                break
+                ;;
+        esac
+    done
+}
+
+parse_opts "$@"
+shift $((OPTIND - 1))
 
 if [[ ! -f "/etc/os-release" ]]; then
     echo "ERROR: /etc/os-release not found" 1>&2
