reduce the screens opened (just edit, server, log)

diff --git a/rails_in_screen b/rails_in_screen
--- a/rails_in_screen
+++ b/rails_in_screen
@@ -1,18 +1,22 @@
 #!/usr/bin/env bash
 
-if [ ! -d "$1" ]; then
-    echo "ERROR: You picked an invalid directory: '$1'" 1>&2 
+if [ -z "$1" ]; then
+    dir=$(pwd)
+else
+    dir=$1
+fi
+
+if [ ! -d "$dir" ]; then
+    echo "ERROR: Invalid directory: $dir" 1>&2 
     exit 1
 fi
 
 if [ ! -n "$STY" ]; then
-    echo "ERROR: You're not inside a screen session." 1>&2 
+    echo "ERROR: No screen session found." 1>&2 
     exit 1
 fi
 
-cd $1
-screen -t gsvr gem server
-screen -t wsvr
-screen -t log tail -f log/development.log
-screen -t shell
+cd $dir
 screen -t edit vim
+screen -t server
+screen -t log tail -f log/development.log
