Make 'return' and 'exit' now that we're in a file, not .bashrc.

diff --git a/tmux_new_project b/tmux_new_project
--- a/tmux_new_project
+++ b/tmux_new_project
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -e
+
 # Create a new tmux session in a project directory.
 
 if [ $# -lt 1 ]; then
@@ -10,7 +12,7 @@ fi
 
 directory=$1
 session_name=$(basename $directory)
-test -d $directory || { echo "ERROR: no directory: $directory" 1>&2; return 1; }
+test -d $directory || { echo "ERROR: no directory: $directory" 1>&2; exit 1; }
 
 (
     cd $directory
